### PR TITLE
Update .NET to VS2015 format

### PR DESCRIPTION
**Pull request by LeeCampbell**
Just a small update to bring the .NET code to the new VisualStudio 2015 format. This allows devs to use the (free) VS2015 Community SKU to code against it.

### CODE REVIEW

**Comment by mattwarren** [comment]
@LeeCampbell thanks for doing this, it's been a while since I did anything for the .NET version of HdrHistogram, it's nice to know it's being used somewhere!!

I'll take a look at this over the next few days.

**Comment by LeeCampbell** [comment]
Hey Matt, just FYI we are doing a full re-write of the HdrHistogram for .NET. The main things being pulling it out of the java repo and making it fully .NET (not .NET that looks like java). Will be getting in touch with Gil once we have the build packaging to nuget for .NET45 and PCL.

https://github.com/LeeCampbell/HdrHistogram.NET

The plan is (if Gil agrees) is to have it hosted here in the HdrHistogram org, but under HdrHistogram.NET repo.

**Comment by mattwarren** [comment]
I'm glad you pinged me, I've just started exactly the same thing! Although as you can see at  https://github.com/HdrHistogram/HdrHistogram.NET I'm a long way behind you!

My plan was to start from the latest Java code and do a straight port across, file-by-file. The Java version of HdrHistogram has changed *alot* since I did my original port.

However it looks like your port is much further ahead and you've taken the time to make it look more like .NET, so I think that's a better way to go. You should definitely ping Gil to get permission to commit to the HdrHistogram org, he's always been very happy to see people porting HdrHistogram!

One question, how are you planning to deal with the many re-factorings/updates/fixes that have happened in the Java source since my original port? I.e. how are you going to get the code up-to date with [HdrHistogram-2.1.7](https://github.com/HdrHistogram/HdrHistogram/releases/tag/HdrHistogram-2.1.7)?

**Comment by LeeCampbell** [comment]
The plan is to target features, not lines of code. So I suppose we start off small and target the basic (Long)Histogram, then ensure that it have the same features that the current java version has. Then we add the `Short` and `Int` implementations.

As features get added to the Java version then we can identify them and add them as issues if appropriate to the .NET version.

Thoughts?

**Comment by mattwarren** [comment]
> The plan is to target features, not lines of code

Yeah that sound like a sensible way to go, my line-by-line port only works if it's going to end up looking like a Java port, rather than being fully .NET.

I'm happy to help if you want? (although from the looks of it at the moment you have more time to work on this than I do)

I guess once you've got your code into the main repo, between us we could create a few issues to divide up the reaming work?

> As features get added to the Java version then we can identify them and add them as issues if appropriate to the .NET version.

Yes, that's a good way of tracking things going forward.

**Comment by mattwarren** [comment]
BTW shameless plug, but I know you and the others @AdaptiveLimited are interested in performance.

I'm also working on a Benchmarking library called [BenchmarkDotNet](https://github.com/PerfDotNet/BenchmarkDotNet/) that is designed to make micro-benchmarks easy.

Next time you need to benchmark something you should try it out, here's a [sample benchmark](https://github.com/PerfDotNet/BenchmarkDotNet/blob/master/BenchmarkDotNet.Samples/Introduction/Intro_00_Basic.cs):

``` csharp
// It is very easy to use BenchmarkDotNet. You should just create a class
public class Intro_00_Basic
{
	// And define a method with the Benchmark attribute
	[Benchmark]
	public void Sleep()
	{
		Thread.Sleep(100);
	}

	// You can write description for a method.
	[Benchmark("Thread.Sleep(100)")]
	public void SleepWithDescription()
	{
		Thread.Sleep(100);
	}

	// Now you can run this benchmark competition with help of BenchmarkRunner:
	// new BenchmarkRunner().Run(new Intro_00_Basic());
}
```

**Comment by LeeCampbell** [comment]
I like the look of the new Benchmark Lib. I hand rolled a poor-man's version of that for some of my perf work I have done for the Rx.Net project. This looks like a nice consolidation of that work.

Currently I have some time, but also some start are aligning such that I can get some extra manpower form other Adaptive colleagues to help too. We have an internal push to see what .NET libs we can get running on linux. This one is ripe for the picking. Hope to have something ready end of week.

Once we have that done, I think I will start porting feature by feature to your repo.

**Comment by mattwarren** [comment]
Yeah I'm sure most people have their own hand-rolled benchmark runner, that one of the main reasons we wanted to make a re-usable library, save everyone time!

Plus we can then add features like [printing out the assembly code of the benchmarked method](https://twitter.com/matthewwarren/status/667665291028111364), amongst other things.

> Once we have that done, I think I will start porting feature by feature to your repo.

Okay I'll look out for that and when it's done I'll ping you and see where/if I can help out.

**Comment by giltene** [comment]
A couple of thoughts:

1. We can probably move this discussion to gitter.

2. A feature port will probably work fine. Both C and Python have good ports going that way.

3. I'd consider a good starting target feature set to include:
- a Histogram with signed 64 bit counts
- support auto-sizing
- support for percentile, linear, and log based iteration (via whatever idiomatic iteration scheme works for .net).
- Support for SingleWriterRecorder. It turns out to be such a popular pattern for using histograms (record in latency-critical path, log from another thread) that going without it seems "wrong".
- Consider supporting Recorder (which supports multiple concurrent writers), but that will also require a ConcurrentHistogram.
- The ability to encode into the compressed V2 serialized histogram format (which is what the current Java code will encode to, as well as the current C and Python code bases).
- The ability to decode V2. Extra credit: decide V0 and V1 as well (both C and Python do this now). Test logs with V2, V1, and V0 encoded histograms are included in the Java repo under test/resources.
- Support a log writer that would output V2 encoded histograms to a log file compatible with HistogramLogWriter
- Support for a log reader to match.


Sent from Gil's iPhone

On Nov 24, 2015, at 5:02 AM, Lee Campbell <notifications@github.com<mailto:notifications@github.com>> wrote:


The plan is to target features, not lines of code. So I suppose we start off small and target the basic (Long)Histogram, then ensure that it have the same features that the current java version has. Then we add the Short and Int implementations.

As features get added to the Java version then we can identify them and add them as issues if appropriate to the .NET version.

Thoughts?

**Pull request merged**
