### PR TITLE
Add module-info via moditect

### PR DESCRIPTION
**Pull request by bowbahdoe**
This adds an explicit module info using the moditect maven plugin. 

Reference for how I ended up here

https://github.com/micrometer-metrics/micrometer/issues/4990

### CODE REVIEW

**Comment by bowbahdoe** [comment]
Also @giltene - let me know if you would like a bribe. I'll venmo you enough for / order you a 🍕 .

**Comment by giltene** [comment]
@bowbahdoe Can you verify that the moditect behavior in the newly released HdrHistogram 2.2.1 works for your purposes?

**Comment by bowbahdoe** [comment]
This is all on me. It was a combination of a few factors:

* I've been using moditect successfully on projects up until now
* I was having trouble getting java 7 compilation to work so i figured..eh its probably fine (i read through every file to make sure there were no service providers or imports outside of java.base - thats usually the easiest case)

My current guess is that moditect has some dumb `NamedLikeThis.package` rule that it infers as `.package` being actually an inner class.

**Comment by giltene** [comment]
Yes, it seems like however moditect is creating the actual module-info.class file to put in the jar, it is somehow converting module-info.java that it generated, and that looks like this:
```
% cat target/moditect/generated-sources/org.HdrHistogram/module-info.java
module org.HdrHistogram {
    exports org.HdrHistogram;
    exports org.HdrHistogram.packedarray;
}
```


to a module-info.class file that looks like this:

```
% javap META-INF/versions/9/module-info.class
module org.HdrHistogram@2.2.2-SNAPSHOT {
  requires java.base;
  exports org.HdrHistogram;
  exports org.HdrHistogram$packedarray;
}
```
A normal javac of a module-info.java with the same contents doesn't do that strange "dot to dollar" seemingly-mistaken conversion. 

This doesn't currently break anything for non-users-of-module-info, but seems to not be enough for module-info consumers to be happy. Let's work to figure out the mechanics to make it do it right...

Note: BTW, it's worth noting that it is not actually necessary for the .packedarray package to be exported (unless people want to use it directly), but it seems like removing it (from the moditect listed set of exports) makes a module-info.class file that does what you'd think is ok (make no mention of the .packedarray package in exports), but then breaks the outcome on the consumer side (e.g. LatencyUtils trying to also use moditect) with a complaint about " Invocation of jdeps failed:"... (where it currently break with "Package org.HdrHistogram$packedarray not found in module").

**Comment by karianna** [comment]
@giltene I may have discovered a downstream challenge with this. The Maven Surefire plugin does not seem to be able to read the module using Maven 3.9.7, Java 11.0.23 and latest plugins:

[DEBUG] Forking command line: /bin/sh -c cd '/Users/martijnverburg/workspace/microsoft/Censum/censum-ui/censum-desktop' && '/Library/Java/JavaVirtualMachines/temurin-11.jdk/Contents/Home/bin/java' '@/Users/martijnverburg/workspace/microsoft/Censum/censum-ui/censum-desktop/target/surefire/surefireargs-20240529185813763_18' '/Users/martijnverburg/workspace/microsoft/Censum/censum-ui/censum-desktop/target/surefire' '2024-05-29T18-58-08_261-jvmRun1' 'surefire-20240529185813763_16tmp' 'surefire_5-20240529185813763_17tmp'
[DEBUG] Fork Channel [1] connected to the client.
[ERROR] Error occurred during initialization of boot layer
**[ERROR] java.lang.module.FindException: Error reading module: /Users/martijnverburg/.m2/repository/org/hdrhistogram/HdrHistogram/2.2.1/HdrHistogram-2.2.1.jar
[DEBUG] Caused by: java.lang.module.InvalidModuleDescriptorException: Package org.HdrHistogram$packedarray not found in module**
[DEBUG] Closing the fork 1 after not saying Good Bye.

I can confirm that `/Users/martijnverburg/.m2/repository/org/hdrhistogram/HdrHistogram/2.2.1/HdrHistogram-2.2.1.jar` is there and that it contains a file: `META-INF/versions/9/module-info.class`.

**Comment by aalmiray** [comment]
A fix has been proposed to ModiTect https://github.com/moditect/moditect/pull/250

**Comment by giltene** [comment]
I've reverted the modtect use for now, and released [HdrHistogram 2.2.2](https://github.com/HdrHistogram/HdrHistogram/releases/tag/HdrHistogram-2.2.2) without it (and without a module-info.class, just MANIFEST.MF with Automatic-Module-Name). Let's get back to using moditect once https://github.com/moditect/moditect/issues/249 is resolved.

**Comment by vietj** [comment]
There is another proposal for this : https://github.com/HdrHistogram/HdrHistogram/pull/208

**Pull request merged**
